/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class NativeReader {
  /** `sheet_name` wins over `sheet_index`; with neither, the first sheet is read. */
  constructor(path: string, sheetIndex?: number | undefined | null, sheetName?: string | undefined | null, batchSize?: number | undefined | null)
  /** Resolves to an array of row arrays, or null when the sheet is exhausted. */
  next(): Promise<unknown>
  /** Stops the worker early and releases the file. */
  close(): void
}

export declare class NativeWriter {
  constructor(path: string, mode?: string | undefined | null)
  /** Adds a sheet and returns its index. */
  addSheet(name: string, columns?: Array<string> | undefined | null, header?: boolean | undefined | null): number
  /** Writes one batch of rows (arrays or plain objects). Returns rows written. */
  writeRows(sheet: number, rows: unknown[]): number
  /** Drops the workbook and its temp files without writing anything. */
  abort(): void
  /** Finishes the workbook on a worker thread. The writer is unusable afterwards. */
  close(): Promise<unknown>
}

export declare function listSheets(path: string): Promise<unknown>

export interface SheetInfo {
  name: string
  index: number
}

export interface WriteResult {
  rows: number
  bytes: number
}
