import { XlsxWriter, readXlsx } from 'sheetstream'

const w = new XlsxWriter('report.xlsx', { mode: 'lowMemory' })
const orders = w.addSheet('Orders', { columns: ['id', 'total'] })
const notes = w.addSheet('Notes')

orders.writeRows([{ id: 1, total: 9.5 }, { id: 2, total: 20 }])
notes.writeRows([['Generated by sheetstream'], ['Second note']])

console.log(await w.close()) // { rows, bytes }
console.log(await readXlsx('report.xlsx', { sheet: 'Orders' }).toArray())
